"""HTML serialization of audit results.

Produces a standalone HTML report (no external dependencies, no JavaScript).
Suitable for saving to a file, attaching to tickets, or serving from a web server.

Usage:
    from bob.html_output import build_html_output
    print(build_html_output(engine, sys_info, t))

M-4 (v0.7.2): all user-facing strings are now sourced from the translation
function ``t`` (or the hardcoded English fallback dict ``_FALLBACK_LABELS``
when ``t=None``). The ``<html lang="...">`` attribute is set from the
optional ``lang`` parameter (defaults to "en"). Same shape as
``bob/markdown_output.py``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from html import escape

from bob.report import SystemInfo
from bob.scoring import FindingLevel, ScoreEngine

# M-4 (v0.7.2): translation key per level (the displayed string is
# i18n-rendered at render time). The keys here map to entries in the
# ``html_output`` namespace; the fallback dict supplies English defaults.
_LEVEL_LABEL_KEY: dict[FindingLevel, str] = {
    FindingLevel.ALERT: "html_output.level_alert",
    FindingLevel.WARN:  "html_output.level_warn",
    FindingLevel.INFO:  "html_output.level_info",
    FindingLevel.OK:    "html_output.level_ok",
}

_LEVEL_COLOR: dict[FindingLevel, str] = {
    FindingLevel.ALERT: "#dc3545",
    FindingLevel.WARN:  "#fd7e14",
    FindingLevel.INFO:  "#0d6efd",
    FindingLevel.OK:    "#198754",
}

_LEVEL_ORDER = [FindingLevel.ALERT, FindingLevel.WARN, FindingLevel.INFO, FindingLevel.OK]


# M-4 (v0.7.2): English fallback strings used when no ``t`` function is passed.
_FALLBACK_LABELS = {
    "html_output.title_prefix":        "BOB",
    "html_output.report_title":        "BOB Report",
    "html_output.field_score":         "Score",
    "html_output.field_alerts":        "Alerts",
    "html_output.field_warnings":      "Warnings",
    "html_output.field_host":          "Host",
    "html_output.field_os":            "OS",
    "html_output.field_kernel":        "Kernel",
    "html_output.field_timestamp":     "Timestamp",
    "html_output.heading_deductions":  "Score Deductions",
    "html_output.col_points":          "Points",
    "html_output.col_reason":          "Reason",
    "html_output.col_message":         "Message",
    "html_output.col_fix_command":     "Fix command",
    "html_output.no_findings":         "No findings detected.",
    "html_output.findings_count":      "{count} finding(s)",
    "html_output.level_alert":         "ALERT",
    "html_output.level_warn":          "WARN",
    "html_output.level_info":          "INFO",
    "html_output.level_ok":            "OK",
    "html_output.footer":
        'Generated by <a href="https://github.com/Masbateno/bodyguard-of-bits">BOB</a>. '
        'Commands shown are suggestions — review before executing.',
    "html_output.risk_unknown":        "UNKNOWN",
    # M-12 (v0.7.3): translated risk-level labels for the summary header.
    "html_output.risk_low":            "LOW",
    "html_output.risk_medium":         "MEDIUM",
    "html_output.risk_high":           "HIGH",
    "html_output.risk_critical":       "CRITICAL",
    "html_output.note_label":          "Note",
    "html_output.detail_label":        "Detail",
}


def _fallback_t(key: str, **kw) -> str:
    """Default ``t`` function used when no caller-supplied translator is
    available. Returns the English fallback or the key itself if missing
    so a typo is immediately visible. Supports ``{count}``-style format
    placeholders."""
    val = _FALLBACK_LABELS.get(key, key)
    if kw:
        try:
            return val.format(**kw)
        except (KeyError, IndexError, ValueError):
            return val
    return val


def _score_color(score: int) -> str:
    if score >= 8:
        return "#198754"
    if score >= 5:
        return "#fd7e14"
    return "#dc3545"


def _h(text: str) -> str:
    """HTML-escape a string."""
    return escape(str(text), quote=True)


_CSS = """\
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
         background:#f8f9fa;color:#212529;padding:2rem}
    h1{font-size:1.5rem;margin-bottom:1rem;color:#343a40}
    h2{font-size:1.1rem;margin:1.5rem 0 .5rem;color:#495057;border-bottom:1px solid #dee2e6;
       padding-bottom:.25rem}
    table{width:100%;border-collapse:collapse;font-size:.9rem;background:#fff;
          border-radius:6px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.1)}
    th{background:#343a40;color:#fff;padding:.5rem .75rem;text-align:left;font-weight:600}
    td{padding:.45rem .75rem;border-bottom:1px solid #dee2e6;vertical-align:top}
    tr:last-child td{border-bottom:none}
    tr:nth-child(even) td{background:#f8f9fa}
    .score-circle{display:inline-block;width:3.5rem;height:3.5rem;border-radius:50%;
                  line-height:3.5rem;text-align:center;font-size:1.4rem;font-weight:700;
                  color:#fff}
    .badge{display:inline-block;padding:.2em .55em;border-radius:4px;font-size:.75rem;
           font-weight:700;color:#fff;white-space:nowrap}
    code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;
         background:#e9ecef;padding:.1em .35em;border-radius:3px;font-size:.82rem;
         word-break:break-all}
    .meta-grid{display:grid;grid-template-columns:auto 1fr;gap:.25rem .75rem;
               font-size:.9rem;margin-bottom:1.5rem}
    .meta-grid dt{font-weight:600;color:#6c757d}
    .finding-detail{margin-top:.25rem;font-size:.82rem;color:#495057}
    .finding-note{margin-top:.25rem;font-size:.82rem;color:#6c757d;font-style:italic}
    footer{margin-top:2rem;font-size:.8rem;color:#6c757d}
"""


def build_html_output(
    engine: ScoreEngine,
    sys_info: SystemInfo,
    t=None,
    lang: str = "en",
) -> str:
    """Return a standalone HTML string with the full audit report.

    Args:
        engine:   The audit ScoreEngine after ``finalize()``.
        sys_info: Populated SystemInfo for the host.
        t:        Optional translation function ``t(key, **kwargs) -> str``.
                  When ``None`` (legacy / test path), an English fallback is
                  used. Production callers should pass the audit's bound
                  ``t``.
        lang:     ISO 639-1 language code emitted as the ``<html lang="">``
                  attribute. Defaults to "en" matching the English fallback.
    """
    if t is None:
        t = _fallback_t
    ts         = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    score      = engine.score
    s_color    = _score_color(score)
    # I-1 (v0.7.0 Phase 2.1): use effective_level (posture-aware) for the
    # displayed risk, matching display/JSON/CSV/webhook contracts. Fallback
    # to engine.level for legacy test mocks that don't populate the new
    # property.
    # M-12 (v0.7.3): the displayed risk label is now translated. Pre-v0.7.3
    # the summary header showed the raw English value upper-cased ("LOW",
    # "HIGH") regardless of locale, while the finding badges below were
    # already translated through _LEVEL_LABEL_KEY. Now both surfaces use
    # the same i18n contract.
    _eff_level = getattr(engine, "effective_level", engine.level)
    if _eff_level is not None:
        # Try a locale key like html_output.risk_low / risk_medium / ...;
        # fall back to the upper-cased value so unknown enum values still
        # surface something visible.
        _risk_key = f"html_output.risk_{_eff_level.value}"
        level_label = t(_risk_key)
        if level_label == _risk_key:
            level_label = str(_eff_level.value).upper()
    else:
        level_label = t("html_output.risk_unknown")

    parts: list[str] = []
    a = parts.append

    a("<!DOCTYPE html>")
    a(f'<html lang="{_h(lang)}">')
    a("<head>")
    a('<meta charset="utf-8">')
    a('<meta name="viewport" content="width=device-width,initial-scale=1">')
    a(f"<title>{_h(t('html_output.title_prefix'))} — {_h(sys_info.hostname)} — {_h(ts)}</title>")
    a(f"<style>{_CSS}</style>")
    a("</head>")
    a("<body>")

    a(f"<h1>{_h(t('html_output.report_title'))} — {_h(sys_info.hostname)}</h1>")

    # --- Summary ---
    a('<dl class="meta-grid">')
    a(f"<dt>{_h(t('html_output.field_score'))}</dt><dd>"
      f'<span class="score-circle" style="background:{_h(s_color)}">{score}</span>'
      f" / 10 &nbsp; <strong>{_h(level_label)}</strong></dd>")
    a(f"<dt>{_h(t('html_output.field_alerts'))}</dt><dd>{engine.alert_count}</dd>")
    a(f"<dt>{_h(t('html_output.field_warnings'))}</dt><dd>{engine.warn_count}</dd>")
    a(f"<dt>{_h(t('html_output.field_host'))}</dt><dd><code>{_h(sys_info.hostname)}</code></dd>")
    a(f"<dt>{_h(t('html_output.field_os'))}</dt><dd>{_h(sys_info.os_name)}</dd>")
    a(f"<dt>{_h(t('html_output.field_kernel'))}</dt><dd>{_h(sys_info.kernel)}</dd>")
    a(f"<dt>{_h(t('html_output.field_timestamp'))}</dt><dd>{_h(ts)}</dd>")
    a("</dl>")

    # --- Score deductions ---
    deductions = [d for d in engine.breakdown if d.points > 0]
    if deductions:
        a(f"<h2>{_h(t('html_output.heading_deductions'))}</h2>")
        a(f"<table><thead><tr><th>{_h(t('html_output.col_points'))}</th>"
          f"<th>{_h(t('html_output.col_reason'))}</th></tr></thead><tbody>")
        for d in deductions:
            a(f"<tr><td><strong>−{d.points}</strong></td><td>{_h(d.reason)}</td></tr>")
        a("</tbody></table>")

    # --- Findings by severity ---
    findings_by_level: dict[FindingLevel, list] = {lvl: [] for lvl in _LEVEL_ORDER}
    for f in engine.findings:
        if f.level in findings_by_level:
            findings_by_level[f.level].append(f)

    if not engine.findings:
        a(f"<p>{_h(t('html_output.no_findings'))}</p>")

    for level in _LEVEL_ORDER:
        group = findings_by_level[level]
        if not group:
            continue
        color = _LEVEL_COLOR[level]
        label = t(_LEVEL_LABEL_KEY[level])
        findings_count_str = t("html_output.findings_count", count=len(group))
        a(f'<h2><span class="badge" style="background:{_h(color)}">{_h(label)}</span>'
          f" &nbsp; {_h(findings_count_str)}</h2>")
        a(f"<table><thead><tr><th>{_h(t('html_output.col_message'))}</th>"
          f"<th>{_h(t('html_output.col_fix_command'))}</th></tr></thead><tbody>")
        for f in group:
            # v0.8.0 drift batch (Tier 9): surface note + detail in the
            # message cell so HTML/Markdown reports carry the same
            # operator-relevant context as terminal + JSON output.
            # Pre-v0.8.0, note and detail were silently dropped from
            # these reports.
            msg_html = _h(f.message or "")
            if f.detail:
                msg_html += (
                    f'<div class="finding-detail"><em>'
                    f'{_h(t("html_output.detail_label"))}: '
                    f'{_h(f.detail)}</em></div>'
                )
            if f.note:
                msg_html += (
                    f'<div class="finding-note"><em>'
                    f'{_h(t("html_output.note_label"))}: '
                    f'{_h(f.note)}</em></div>'
                )
            cmd = f"<code>{_h(f.cmd)}</code>" if f.cmd else ""
            a(f"<tr><td>{msg_html}</td><td>{cmd}</td></tr>")
        a("</tbody></table>")

    # Footer is rendered as raw HTML (contains an anchor); avoid double-escape.
    a(f"<footer>{t('html_output.footer')}</footer>")
    a("</body></html>")

    return "\n".join(parts)
