"""Markdown serialization of audit results.

Produces a GitHub-flavored Markdown report suitable for wikis, README
files, issue trackers, or any tool that renders Markdown.

Usage:
    from bob.markdown_output import build_markdown_output
    print(build_markdown_output(engine, sys_info, t))

M-4 (v0.7.2): all user-facing strings are now sourced from the
translation function ``t`` (or the hardcoded English fallback dict
``_FALLBACK_LABELS`` when ``t=None``). Production callers must pass
the audit's bound ``t``; tests that don't pass it see the English
defaults so they don't have to set up i18n. The fallback dict is the
documented baseline for future translators — copy its values into
``bob/locales/<lang>.json`` under the ``markdown_output`` namespace.
"""

from __future__ import annotations

from datetime import datetime, timezone

from bob.report import SystemInfo
from bob.scoring import FindingLevel, ScoreEngine

# Severity order for section grouping (most critical first)
_LEVEL_ORDER = [FindingLevel.ALERT, FindingLevel.WARN, FindingLevel.INFO, FindingLevel.OK]

# M-4 (v0.7.2): emoji prefixes for level labels — i18n-independent so they
# stay the same across all locales. Combined with the translated label at
# render time.
_LEVEL_EMOJI = {
    FindingLevel.ALERT: "🔴",
    FindingLevel.WARN:  "🟡",
    FindingLevel.INFO:  "🔵",
    FindingLevel.OK:    "✅",
}

_LEVEL_LABEL_KEY = {
    FindingLevel.ALERT: "markdown_output.section_alerts",
    FindingLevel.WARN:  "markdown_output.section_warnings",
    FindingLevel.INFO:  "markdown_output.section_informational",
    FindingLevel.OK:    "markdown_output.section_ok",
}

_RISK_EMOJI = {
    "low":      "🟢",
    "medium":   "🟡",
    "high":     "🟠",
    "critical": "🔴",
}

# M-4 (v0.7.2): English fallback strings used when no ``t`` function is
# passed. Populating ``bob/locales/en.json`` with these under the
# ``markdown_output`` namespace would let the runtime ``t`` function
# satisfy them; until then the fallback keeps existing tests + legacy
# callers producing the v0.7.1 English output.
_FALLBACK_LABELS = {
    "markdown_output.report_title":           "BOB Report",
    "markdown_output.heading_summary":        "Summary",
    "markdown_output.heading_deductions":     "Score Deductions",
    "markdown_output.col_field":              "Field",
    "markdown_output.col_value":              "Value",
    "markdown_output.col_points":             "Points",
    "markdown_output.col_reason":             "Reason",
    "markdown_output.col_message":            "Message",
    "markdown_output.col_fix_command":        "Fix command",
    "markdown_output.field_score":            "Score",
    "markdown_output.field_risk_level":       "Risk level",
    "markdown_output.field_alerts":           "Alerts",
    "markdown_output.field_warnings":         "Warnings",
    "markdown_output.field_host":             "Host",
    "markdown_output.field_os":               "OS",
    "markdown_output.field_kernel":           "Kernel",
    "markdown_output.field_timestamp":        "Timestamp",
    "markdown_output.section_alerts":        "Alerts",
    "markdown_output.section_warnings":      "Warnings",
    "markdown_output.section_informational": "Informational",
    "markdown_output.section_ok":            "OK",
    "markdown_output.risk_unknown":           "unknown",
    "markdown_output.footer":
        "_Generated by [BOB](https://github.com/Masbateno/bodyguard-of-bits). "
        "Commands shown are suggestions — review before executing._",
}


def _fallback_t(key: str, **_kw) -> str:
    """Default ``t`` function used when the caller doesn't pass one.

    Returns the English fallback string for *key* if known, otherwise the
    key itself so a missing localisation is immediately visible to the
    developer (rather than silently producing empty output)."""
    return _FALLBACK_LABELS.get(key, key)


def _md_escape(text: str) -> str:
    """Escape pipe characters so they don't break Markdown tables."""
    return text.replace("|", "\\|").replace("\n", " ")


def build_markdown_output(
    engine: ScoreEngine,
    sys_info: SystemInfo,
    t=None,
) -> str:
    """Return a Markdown string with the full audit report.

    Args:
        engine:   The audit ScoreEngine after ``finalize()``.
        sys_info: Populated SystemInfo for the host.
        t:        Optional translation function ``t(key, **kwargs) -> str``.
                  When ``None`` (legacy / test path), an English fallback is
                  used. Production callers should pass the audit's bound
                  ``t`` so the Markdown export matches the locale chosen by
                  the operator.
    """
    if t is None:
        t = _fallback_t
    ts  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    # I-1 (v0.7.0 Phase 2.1): use effective_level (posture-aware) for the
    # displayed risk, matching display/JSON/CSV/webhook contracts. Fallback
    # to engine.level for legacy test mocks that don't populate the new
    # property.
    # I-6 (v0.7.3): converge with bob/html_output.py on the safer
    # ``is not None`` + ``.value`` access pattern. Pre-v0.7.3 a mock with
    # ``effective_level = SomeObj()`` (no ``.value`` attr) silently fell
    # through to ``risk_unknown`` instead of surfacing the type confusion.
    _eff_level = getattr(engine, "effective_level", engine.level)
    if _eff_level is not None:
        level_value = _eff_level.value
        risk_emoji  = _RISK_EMOJI.get(level_value, "")
        level_label = level_value.capitalize()
    else:
        level_value = ""
        risk_emoji  = ""
        level_label = t("markdown_output.risk_unknown")

    lines: list[str] = []

    # --- Header ---
    lines.append(f"# {t('markdown_output.report_title')} — {sys_info.hostname} — {ts}")
    lines.append("")

    # --- Summary table ---
    lines.append(f"## {t('markdown_output.heading_summary')}")
    lines.append("")
    lines.append(f"| {t('markdown_output.col_field')} | {t('markdown_output.col_value')} |")
    lines.append("|-------|-------|")
    lines.append(f"| **{t('markdown_output.field_score')}** | {engine.score}/10 |")
    lines.append(f"| **{t('markdown_output.field_risk_level')}** | {risk_emoji} {level_label} |")
    lines.append(f"| **{t('markdown_output.field_alerts')}** | {engine.alert_count} |")
    lines.append(f"| **{t('markdown_output.field_warnings')}** | {engine.warn_count} |")
    lines.append(f"| **{t('markdown_output.field_host')}** | `{sys_info.hostname}` |")
    lines.append(f"| **{t('markdown_output.field_os')}** | {sys_info.os_name} |")
    lines.append(f"| **{t('markdown_output.field_kernel')}** | {sys_info.kernel} |")
    lines.append(f"| **{t('markdown_output.field_timestamp')}** | {ts} |")
    lines.append("")

    # --- Score deductions ---
    deductions = [d for d in engine.breakdown if d.points > 0]
    if deductions:
        lines.append(f"## {t('markdown_output.heading_deductions')}")
        lines.append("")
        lines.append(f"| {t('markdown_output.col_points')} | {t('markdown_output.col_reason')} |")
        lines.append("|--------|--------|")
        for d in deductions:
            lines.append(f"| -{d.points} | {_md_escape(d.reason)} |")
        lines.append("")

    # --- Findings by level ---
    findings_by_level = {lvl: [] for lvl in _LEVEL_ORDER}
    for f in engine.findings:
        if f.level in findings_by_level:
            findings_by_level[f.level].append(f)

    for level in _LEVEL_ORDER:
        group = findings_by_level[level]
        if not group:
            continue
        lines.append(f"## {_LEVEL_EMOJI[level]} {t(_LEVEL_LABEL_KEY[level])}")
        lines.append("")
        lines.append(f"| {t('markdown_output.col_message')} | {t('markdown_output.col_fix_command')} |")
        lines.append("|---------|-------------|")
        for f in group:
            msg = _md_escape(f.message or "")
            cmd = f"`{_md_escape(f.cmd)}`" if f.cmd else ""
            lines.append(f"| {msg} | {cmd} |")
        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append("")
    lines.append(t("markdown_output.footer"))
    lines.append("")

    return "\n".join(lines)
