"""Markdown serialization of audit results.

Produces a GitHub-flavored Markdown report suitable for wikis, README
files, issue trackers, or any tool that renders Markdown.

Usage:
    from bob.markdown_output import build_markdown_output
    print(build_markdown_output(engine, sys_info))
"""

from __future__ import annotations

from datetime import datetime, timezone

from bob.report import SystemInfo
from bob.scoring import FindingLevel, ScoreEngine

# Severity order for section grouping (most critical first)
_LEVEL_ORDER = [FindingLevel.ALERT, FindingLevel.WARN, FindingLevel.INFO, FindingLevel.OK]

_LEVEL_LABEL = {
    FindingLevel.ALERT: "🔴 Alerts",
    FindingLevel.WARN:  "🟡 Warnings",
    FindingLevel.INFO:  "🔵 Informational",
    FindingLevel.OK:    "✅ OK",
}

_RISK_EMOJI = {
    "low":      "🟢",
    "medium":   "🟡",
    "high":     "🟠",
    "critical": "🔴",
}


def _md_escape(text: str) -> str:
    """Escape pipe characters so they don't break Markdown tables."""
    return text.replace("|", "\\|").replace("\n", " ")


def build_markdown_output(
    engine: ScoreEngine,
    sys_info: SystemInfo,
) -> str:
    """Return a Markdown string with the full audit report."""
    ts  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    # I-1 (v0.7.0 Phase 2.1): use effective_level (posture-aware) for the
    # displayed risk, matching display/JSON/CSV/webhook contracts. Fallback
    # to engine.level for legacy test mocks that don't populate the new
    # property.
    _eff_level = getattr(engine, "effective_level", engine.level)
    level_value = getattr(_eff_level, "value", "") if _eff_level is not None else ""
    risk_emoji  = _RISK_EMOJI.get(level_value, "")
    level_label = level_value.capitalize() if level_value else "unknown"

    lines: list[str] = []

    # --- Header ---
    lines.append(f"# BOB Report — {sys_info.hostname} — {ts}")
    lines.append("")

    # --- Summary table ---
    lines.append("## Summary")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| **Score** | {engine.score}/10 |")
    lines.append(f"| **Risk level** | {risk_emoji} {level_label} |")
    lines.append(f"| **Alerts** | {engine.alert_count} |")
    lines.append(f"| **Warnings** | {engine.warn_count} |")
    lines.append(f"| **Host** | `{sys_info.hostname}` |")
    lines.append(f"| **OS** | {sys_info.os_name} |")
    lines.append(f"| **Kernel** | {sys_info.kernel} |")
    lines.append(f"| **Timestamp** | {ts} |")
    lines.append("")

    # --- Score deductions ---
    deductions = [d for d in engine.breakdown if d.points > 0]
    if deductions:
        lines.append("## Score Deductions")
        lines.append("")
        lines.append("| Points | Reason |")
        lines.append("|--------|--------|")
        for d in deductions:
            lines.append(f"| -{d.points} | {_md_escape(d.reason)} |")
        lines.append("")

    # --- Findings by level ---
    findings_by_level = {lvl: [] for lvl in _LEVEL_ORDER}
    for f in engine.findings:
        if f.level in findings_by_level:
            findings_by_level[f.level].append(f)

    for level in _LEVEL_ORDER:
        group = findings_by_level[level]
        if not group:
            continue
        lines.append(f"## {_LEVEL_LABEL[level]}")
        lines.append("")
        lines.append("| Message | Fix command |")
        lines.append("|---------|-------------|")
        for f in group:
            msg = _md_escape(f.message or "")
            cmd = f"`{_md_escape(f.cmd)}`" if f.cmd else ""
            lines.append(f"| {msg} | {cmd} |")
        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by [BOB](https://github.com/Masbateno/bodyguard-of-bits). "
        "Commands shown are suggestions — review before executing._"
    )
    lines.append("")

    return "\n".join(lines)
