"""Markdown serialization of audit results.

Produces a GitHub-flavored Markdown report suitable for wikis, README
files, issue trackers, or any tool that renders Markdown.

Usage:
    from bob.markdown_output import build_markdown_output
    print(build_markdown_output(engine, sys_info, t))

M-4 (v0.7.2): all user-facing strings are now sourced from the
translation function ``t`` (or the hardcoded English fallback dict
``_FALLBACK_LABELS`` when ``t=None``). Production callers must pass
the audit's bound ``t``; tests that don't pass it see the English
defaults so they don't have to set up i18n. The fallback dict is the
documented baseline for future translators — copy its values into
``bob/locales/<lang>.json`` under the ``markdown_output`` namespace.
"""

from __future__ import annotations

from datetime import datetime, timezone

from bob.report import SystemInfo
from bob.scoring import FindingLevel, ScoreEngine

# Severity order for section grouping (most critical first)
_LEVEL_ORDER = [FindingLevel.ALERT, FindingLevel.WARN, FindingLevel.INFO, FindingLevel.OK]

# M-4 (v0.7.2): emoji prefixes for level labels — i18n-independent so they
# stay the same across all locales. Combined with the translated label at
# render time.
_LEVEL_EMOJI = {
    FindingLevel.ALERT: "🔴",
    FindingLevel.WARN:  "🟡",
    FindingLevel.INFO:  "🔵",
    FindingLevel.OK:    "✅",
}

_LEVEL_LABEL_KEY = {
    FindingLevel.ALERT: "markdown_output.section_alerts",
    FindingLevel.WARN:  "markdown_output.section_warnings",
    FindingLevel.INFO:  "markdown_output.section_informational",
    FindingLevel.OK:    "markdown_output.section_ok",
}

_RISK_EMOJI = {
    "low":      "🟢",
    "medium":   "🟡",
    "high":     "🟠",
    "critical": "🔴",
}

# M-4 (v0.7.2): English fallback strings used when no ``t`` function is
# passed. Populating ``bob/locales/en.json`` with these under the
# ``markdown_output`` namespace would let the runtime ``t`` function
# satisfy them; until then the fallback keeps existing tests + legacy
# callers producing the v0.7.1 English output.
_FALLBACK_LABELS = {
    "markdown_output.report_title":           "BOB Report",
    "markdown_output.heading_summary":        "Summary",
    "markdown_output.heading_deductions":     "Score Deductions",
    "domain_scores.title":                    "Domain Scores",
    "markdown_output.col_field":              "Field",
    "markdown_output.col_value":              "Value",
    "markdown_output.col_domain":             "Domain",
    "markdown_output.col_score":              "Score",
    "markdown_output.col_status":             "Status",
    "markdown_output.col_points":             "Points",
    "markdown_output.col_reason":             "Reason",
    "markdown_output.col_message":            "Message",
    "markdown_output.col_fix_command":        "Fix command",
    "markdown_output.field_score":            "Score",
    "markdown_output.field_risk_level":       "Risk level",
    "markdown_output.field_alerts":           "Alerts",
    "markdown_output.field_warnings":         "Warnings",
    "markdown_output.field_host":             "Host",
    "markdown_output.field_profile":          "Audit profile",
    "markdown_output.field_os":               "OS",
    "markdown_output.field_kernel":           "Kernel",
    "markdown_output.field_timestamp":        "Timestamp",
    "markdown_output.section_alerts":        "Alerts",
    "markdown_output.section_warnings":      "Warnings",
    "markdown_output.section_informational": "Informational",
    "markdown_output.section_ok":            "OK",
    "markdown_output.risk_unknown":           "unknown",
    "markdown_output.footer":
        "_Generated by [BOB](https://github.com/Masbateno/bodyguard-of-bits). "
        "Commands shown are suggestions — review before executing._",
    "markdown_output.note_label":             "Note",
    "markdown_output.detail_label":           "Detail",
}


# v0.8.2: hand-rolled ``_fallback_t`` consolidated to the shared
# ``bob._i18n_safe.make_fallback_t`` factory. Pre-v0.8.2 this module's
# fallback skipped ``.format()`` entirely (all labels in
# ``_FALLBACK_LABELS`` are static strings without ``{}``, so format
# no-ops). Shared factory always tries format — byte-identical for the
# current label set, defensive against any future label that introduces
# a placeholder.
from bob._i18n_safe import make_fallback_t
_fallback_t = make_fallback_t(_FALLBACK_LABELS)


def _md_escape(text: str) -> str:
    """Neutralise a system-derived string for use inside a Markdown table cell.

    Two different jobs, and until v0.15.0 only the first was done:

    * **Table structure** — an unescaped ``|`` splits the row into extra
      columns and corrupts the table.
    * **Content semantics** — a Markdown cell renders inline HTML, links and
      images. Finding messages carry system-derived values (process names,
      cron commands, file paths, service names), so a crafted one reached the
      report intact: ``<img src=x onerror=…>`` and ``<script>`` executed in any
      renderer that passes HTML through, ``[click](javascript:…)`` rendered as
      a live link, and ``![x](https://…)`` made the auditor's machine fetch a
      remote image the moment they opened their own report.

    The HTML writer escaped all of this via ``html.escape`` from the start;
    this one did not. Same invariant, two output formats, one of them wrong.

    ``<`` is turned into an entity rather than backslash-escaped because
    Markdown does not honour a backslash before ``<``. Escaping ``[`` disables
    both link and image syntax, since an image is a link with a ``!`` in front.
    """
    return (
        text.replace("|", "\\|")
            .replace("\n", " ")
            .replace("<", "&lt;")
            .replace("[", "\\[")
            .replace("]", "\\]")
    )


def _md_code(text: str) -> str:
    """Render *text* as a Markdown code span, fenced so its content survives.

    A code span is not a place for entity escaping — ``&lt;`` inside backticks
    displays as the five characters ``&lt;``, corrupting the command an
    operator is meant to copy. What a code span does need is a fence longer
    than the longest run of backticks inside it, and a space of padding when
    the content starts or ends with one (CommonMark 6.3).
    """
    body = text.replace("|", "\\|").replace("\n", " ")
    longest = 0
    run = 0
    for ch in body:
        run = run + 1 if ch == "`" else 0
        longest = max(longest, run)
    fence = "`" * (longest + 1)
    pad = " " if body.startswith("`") or body.endswith("`") else ""
    return f"{fence}{pad}{body}{pad}{fence}"



def build_markdown_output(
    engine: ScoreEngine,
    sys_info: SystemInfo,
    t=None,
    profile=None,
    config=None,
) -> str:
    """Return a Markdown string with the full audit report.

    Args:
        engine:   The audit ScoreEngine after ``finalize()``.
        sys_info: Populated SystemInfo for the host.
        t:        Optional translation function ``t(key, **kwargs) -> str``.
                  When ``None`` (legacy / test path), an English fallback is
                  used. Production callers should pass the audit's bound
                  ``t`` so the Markdown export matches the locale chosen by
                  the operator.
    """
    if t is None:
        t = _fallback_t
    ts  = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    # I-1 (v0.7.0 Phase 2.1): use effective_level (posture-aware) for the
    # displayed risk, matching display/JSON/CSV/webhook contracts. Fallback
    # to engine.level for legacy test mocks that don't populate the new
    # property.
    # I-6 (v0.7.3): converge with bob/html_output.py on the safer
    # ``is not None`` + ``.value`` access pattern. Pre-v0.7.3 a mock with
    # ``effective_level = SomeObj()`` (no ``.value`` attr) silently fell
    # through to ``risk_unknown`` instead of surfacing the type confusion.
    _eff_level = getattr(engine, "effective_level", engine.level)
    if _eff_level is not None:
        level_value = _eff_level.value
        risk_emoji  = _RISK_EMOJI.get(level_value, "")
        level_label = level_value.capitalize()
    else:
        level_value = ""
        risk_emoji  = ""
        level_label = t("markdown_output.risk_unknown")

    lines: list[str] = []

    # --- Header ---
    lines.append(f"# {t('markdown_output.report_title')} — {sys_info.hostname} — {ts}")
    lines.append("")

    # --- Summary table ---
    lines.append(f"## {t('markdown_output.heading_summary')}")
    lines.append("")
    lines.append(f"| {t('markdown_output.col_field')} | {t('markdown_output.col_value')} |")
    lines.append("|-------|-------|")
    # v0.16.0 — the score is a ceiling when a check could not read its input.
    # Six sinks render it and only two were updated at first; the report an
    # operator archives said 7/10 where the terminal said ≤ 7/10, about the
    # same audit. A guard now covers all of them.
    _sc = f"≤ {engine.score}" if engine.score_is_upper_bound else f"{engine.score}"
    lines.append(f"| **{t('markdown_output.field_score')}** | {_sc}/10 |")
    lines.append(f"| **{t('markdown_output.field_risk_level')}** | {risk_emoji} {level_label} |")
    lines.append(f"| **{t('markdown_output.field_alerts')}** | {engine.alert_count} |")
    lines.append(f"| **{t('markdown_output.field_warnings')}** | {engine.warn_count} |")
    lines.append(f"| **{t('markdown_output.field_host')}** | `{sys_info.hostname}` |")
    # v0.14.1: an archived report must say what it was audited against — the
    # profile changes severities and counts (v0.14.0) and was terminal-only.
    lines.append(f"| **{t('markdown_output.field_profile')}** | "
                 f"`{getattr(profile, 'name', '') or 'server'}` |")
    lines.append(f"| **{t('markdown_output.field_os')}** | {sys_info.os_name} |")
    lines.append(f"| **{t('markdown_output.field_kernel')}** | {sys_info.kernel} |")
    lines.append(f"| **{t('markdown_output.field_timestamp')}** | {ts} |")
    lines.append("")

    # --- Domain scores (ADV-B1, v0.12.1) ---
    # Bring the per-domain breakdown the text + JSON outputs already carry into
    # the Markdown report so an exported/archived report explains the headline.
    from bob.domain_scores import domain_rows
    _rows = domain_rows(engine, t, profile, config)
    if _rows:
        lines.append(f"## {t('domain_scores.title')}")
        lines.append("")
        lines.append(
            f"| {t('markdown_output.col_domain')} | "
            f"{t('markdown_output.col_score')} | {t('markdown_output.col_status')} |"
        )
        lines.append("|--------|--------|--------|")
        for r in _rows:
            _score = f"{r['score']}/10" if r["active"] else "—"
            _status = "" if r["active"] else _md_escape(r["reason"])
            lines.append(f"| {_md_escape(r['label'])} | {_score} | {_status} |")
        lines.append("")

    # --- Score deductions ---
    deductions = [d for d in engine.breakdown if d.points > 0]
    if deductions:
        lines.append(f"## {t('markdown_output.heading_deductions')}")
        lines.append("")
        lines.append(f"| {t('markdown_output.col_points')} | {t('markdown_output.col_reason')} |")
        lines.append("|--------|--------|")
        for d in deductions:
            lines.append(f"| -{d.points} | {_md_escape(d.reason)} |")
        lines.append("")

    # --- Findings by level ---
    findings_by_level = {lvl: [] for lvl in _LEVEL_ORDER}
    for f in engine.findings:
        if f.level in findings_by_level:
            findings_by_level[f.level].append(f)

    for level in _LEVEL_ORDER:
        group = findings_by_level[level]
        if not group:
            continue
        lines.append(f"## {_LEVEL_EMOJI[level]} {t(_LEVEL_LABEL_KEY[level])}")
        lines.append("")
        lines.append(f"| {t('markdown_output.col_message')} | {t('markdown_output.col_fix_command')} |")
        lines.append("|---------|-------------|")
        for f in group:
            msg_parts = [_md_escape(f.message or "")]
            # v0.8.0 drift batch (Tier 9): surface note + detail in the
            # message cell so HTML/Markdown reports carry the same
            # operator-relevant context as terminal + JSON output.
            # Pre-v0.8.0, note and detail were silently dropped from
            # these reports.
            if f.detail:
                msg_parts.append(
                    f"<br>*{_md_escape(t('markdown_output.detail_label'))}: "
                    f"{_md_escape(f.detail)}*"
                )
            if f.note:
                msg_parts.append(
                    f"<br>*{_md_escape(t('markdown_output.note_label'))}: "
                    f"{_md_escape(f.note)}*"
                )
            msg = "".join(msg_parts)
            cmd = _md_code(f.cmd) if f.cmd else ""
            lines.append(f"| {msg} | {cmd} |")
        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append("")
    lines.append(t("markdown_output.footer"))
    lines.append("")

    return "\n".join(lines)
