"""File-patching helpers for cron entries (atomic writes + in-place patches).

Extracted from bob/cron.py in v0.6.0 (#14 split). All file mutations here go
through ``_atomic_write`` to guarantee crash-safety — power loss between
truncate and write would leave cron files empty and silently drop entries
(see v0.5.7 #I-3 for the apply_cron_schedule fix that closed this).

v0.6.1: ``_atomic_write`` is now a thin alias for ``bob._atomic.atomic_write``
(single source of truth across the codebase). The local name is preserved as
a backwards-compat alias because ``tests/test_cron.py::TestApplyCronScheduleAtomic``
patches ``bob.cron._io._atomic_write`` directly.
"""

from __future__ import annotations

import re
import shlex
from datetime import datetime
from pathlib import Path

from bob._atomic import atomic_write as _atomic_write

def _needs_pythonpath() -> bool:
    """Whether the generated script must put the package on PYTHONPATH.

    Answered by asking a clean interpreter — no PYTHONPATH, no inherited
    environment — whether it can import ``bob`` on its own, which is the
    question cron will face. A pip or distro install says yes and needs no
    injection; a checkout run in place says no and does.

    Fails safe: if the probe cannot run at all, the line is emitted, because a
    cron that cannot import BOB does nothing and says nothing.
    """
    import os
    import subprocess
    import sys

    # Same interpreter, same user, no PYTHONPATH, cwd outside the checkout —
    # which is what cron will face, since --install-cron runs under sudo and
    # the generated entry runs as root too. Deliberately NOT setting
    # PYTHONNOUSERSITE: cron's python reads the user site of the account it
    # runs as, so suppressing it here would make the probe stricter than
    # reality and keep emitting a line that is not needed.
    env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
    try:
        return subprocess.run(
            [sys.executable, "-c", "import bob"],
            cwd="/", env=env, capture_output=True, timeout=30,
        ).returncode != 0
    except (OSError, subprocess.SubprocessError):
        return True


def _audit_suffix(audit_options: str) -> str:
    """Validate wizard-chosen audit options and render them as a suffix."""
    if not audit_options:
        return ""
    from ._options import _OPTIONS_RE
    if not _OPTIONS_RE.match(audit_options):
        raise ValueError(f"refusing to write malformed audit options: {audit_options!r}")
    return f" {audit_options}"


def build_script_content(notify_email: str, log_dir: "Path | str",
                         audit_options: str = "") -> str:
    """Build the bash script content for a BOB cron job.

    Args:
        notify_email:  Comma-separated notification addresses ("" for none).
        log_dir:       Where the audit writes its ``.log`` (the mail body).
        audit_options: Extra audit flags chosen in the wizard, as produced by
            ``bob.cron._options.build_audit_options``. Empty (the default)
            reproduces the pre-v0.16.1 command line, which is what every
            already-installed script carries.
    """
    import shutil
    audit_bin = shutil.which("bob") or "/usr/local/bin/bob"
    now_str   = datetime.now().strftime("%Y-%m-%d")
    try:
        # __file__ resolves to bob/cron/_io.py post-v0.6.0 split → parents[2]
        # walks up two levels (cron/ then bob/) and parent.parent gives the
        # bob package's parent dir (PYTHONPATH-able).
        bob_path = str(Path(__file__).parent.parent.parent)
    except (TypeError, AttributeError):
        bob_path = "/usr/local/lib"
    return (
        "#!/bin/bash\n"
        f"# BOB script — generated {now_str} by bob --install-cron\n"
        "# Re-generate: sudo bob --install-cron\n\n"
        f"NOTIFY_EMAILS={shlex.quote(notify_email)}\n"
        f"LOG_DIR={shlex.quote(str(log_dir))}\n"
        # M-3 (v0.7.4): use ``${PYTHONPATH:+:$PYTHONPATH}`` to avoid a
        # trailing colon when PYTHONPATH is unset (the default under cron).
        # A trailing colon makes Python treat the CWD as a search path —
        # a long-standing footgun that BOB previously generated by default.
        #
        # v0.16.2: emitted only when the package cannot be imported without it.
        # The line exists for installs outside pip, where `bob` lives somewhere
        # `sys.path` does not reach. On a normal install it did something else:
        # `--install-cron` run from a git checkout wrote that checkout onto
        # PYTHONPATH, so the nightly audit executed the working tree rather
        # than the installed package — uncommitted edits shipping to production
        # every night, silently. See _needs_pythonpath for how this is decided.
        + (f"export PYTHONPATH={shlex.quote(bob_path)}${{PYTHONPATH:+:$PYTHONPATH}}\n\n"
           if _needs_pythonpath() else "\n")
        # --quiet and --detailed are structural, not preferences: cron has no
        # terminal, and the notification mail *is* the .log that --detailed
        # writes. The wizard's three dimensions are appended (v0.16.1); they
        # arrive pre-validated against closed sets, and are re-checked here
        # because this string lands in a root-owned script.
        + f"{shlex.quote(str(audit_bin))} --quiet --detailed{_audit_suffix(audit_options)}\n"
        "RC=$?\n\n"
        'if [ "$RC" -gt 0 ] && [ -n "$NOTIFY_EMAILS" ]; then\n'
        '    LOG=$(ls -t "$LOG_DIR"/bob_*.log 2>/dev/null | head -1)\n'
        '    if [ -n "$LOG" ]; then\n'
        '        IFS="," read -ra _ADDRS <<< "$NOTIFY_EMAILS"\n'
        '        for _ADDR in "${_ADDRS[@]}"; do\n'
        "            export AUDIT_LOG=\"$LOG\"\n"
        "            export AUDIT_EMAIL=\"$_ADDR\"\n"
        "            export AUDIT_RC=\"$RC\"\n"
        "            python3 << 'PYTHON_EOF'\n"
        "import os, re\n"
        "from bob.report_markdown import send_audit_log_as_html_email\n\n"
        "hostname = os.uname().nodename\n"
        "log_file = os.environ.get('AUDIT_LOG')\n"
        "email = os.environ.get('AUDIT_EMAIL')\n"
        "score = 'N/A'\n"
        "if log_file:\n"
        "    try:\n"
        "        content = open(log_file, encoding='utf-8', errors='replace').read()\n"
        # v0.16.0 — the report renders "Score     : ≤ 7/10" when a check could
        # not read its input. The previous pattern did not match that at all
        # (\\s* does not consume the ≤), so the subject silently became
        # "Score N/A" on any host with one unreadable section — which is most
        # hosts audited without full privileges. The bound is kept in the
        # subject: dropping it would put a plain number on an email whose
        # attached report says a ceiling. The prefix is captured as
        # "any non-digit, non-newline run" rather than the ≤ character, so the
        # generated cron script stays pure ASCII and carries no encoding
        # assumption of its own.
        "        m = re.search(r'Score\\s*:\\s*([^\\d\\n]*)(\\d+/10)', content)\n"
        "        if m:\n"
        "            score = m.group(1).strip() + (' ' if m.group(1).strip() else '') + m.group(2)\n"
        "    except OSError:\n"
        "        pass\n"
        "subject = f'[BOB] {hostname} - Score {score}'\n"
        "if log_file and email:\n"
        "    send_audit_log_as_html_email(log_file, email, subject)\n"
        "PYTHON_EOF\n"
        "        done\n"
        "    fi\n"
        "fi\n"
    )

# ---------------------------------------------------------------------------
# Cron-file mutation helpers — shared between the plain-text wizard
# (edit_cron_schedule / edit_cron_email in _manage.py) and the curses TUI
# (bob/tui/cron.py imports these). Centralising avoids drift between the
# two branches — see v0.4.8 cleanup pass.
# ---------------------------------------------------------------------------

def apply_cron_schedule(entry, schedule_expr: str) -> str:
    """Patch *entry.cron_path* in place with *schedule_expr*.

    Replaces the unique `MIN HOUR DOM MONTH DOW root <script>` line of the
    cron file. Returns an empty string on success, or the OSError string on
    read/write failure (caller renders it to the user).
    """
    try:
        text = entry.cron_path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return str(exc)
    new_line = f"{schedule_expr}  root  {entry.script_path}"
    # M-10 (v0.5.5): anchor first field to cron-token shape
    # ([0-9*,\-/]) to skip comment lines that would otherwise match
    # if their text accidentally fits 5 whitespace-separated tokens
    # followed by " root ". The previous `^\S+\s+...` matched any
    # non-whitespace start including `#`.
    new_text = re.sub(
        r"^[0-9*,\-/]\S*\s+\S+\s+\S+\s+\S+\s+\S+\s+root\s+\S+.*$",
        lambda _: new_line,
        text,
        flags=re.MULTILINE,
    )
    try:
        # I-3 (v0.5.7): atomic write — power-loss between open(O_TRUNC) and
        # write would leave cron file empty and silently drop the entry.
        # Cron files in /etc/cron.d/ must be 0o640 or cron skips them.
        _atomic_write(entry.cron_path, new_text, mode=0o640)
    except OSError as exc:
        return str(exc)
    return ""

def apply_cron_email(entry, new_email: str) -> tuple[str, int]:
    """Patch *entry.cron_path* and the associated wrapper script with *new_email*.

    Accepts the legacy `NOTIFY_EMAIL=` form (no S) in the script for
    backward-compat with pre-v0.3 generated wrappers.

    Returns:
        (error_string, script_subst_count)
        - error_string is "" on success, otherwise the OSError message.
        - script_subst_count is the number of replacements done in the
          wrapper script. 0 indicates the NOTIFY_EMAILS= line was missing
          (the caller may want to warn the user).
    """
    try:
        lines = entry.cron_path.read_text(encoding="utf-8", errors="replace").splitlines()
        updated = [
            f"# email: {new_email}" if ln.startswith("# email:") else ln
            for ln in lines
        ]
        # Cron files in /etc/cron.d/ must be 0o640 (root:root) or cron skips them.
        _atomic_write(entry.cron_path, "\n".join(updated) + "\n", mode=0o640)
    except OSError as exc:
        return (str(exc), 0)

    subst_count = 0
    if entry.script_path.exists():
        try:
            text = entry.script_path.read_text(encoding="utf-8", errors="replace")
            # Match both NOTIFY_EMAILS= (current) and NOTIFY_EMAIL= (legacy)
            text, subst_count = re.subn(
                r"^NOTIFY_EMAILS?=.*$",
                lambda _: f"NOTIFY_EMAILS={shlex.quote(new_email)}",
                text,
                flags=re.MULTILINE,
            )
            # Wrapper script must be 0o755 (executable) — cron exec's it directly.
            _atomic_write(entry.script_path, text, mode=0o755)
        except OSError as exc:
            return (str(exc), subst_count)
    return ("", subst_count)
